# Generated by Django 3.1.6 on 2021-02-05 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(upload_to='Files', verbose_name='File')),
                ('file_title', models.CharField(max_length=255, verbose_name='File Title')),
                ('md5_hash', models.CharField(max_length=50, verbose_name='')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.uploadgroup', verbose_name='Upload Group')),
            ],
        ),
    ]
